######################## default configuration ####################
baseURL = "https://earnonlinemoney.org/"
title = "Earn Money Online | Ulitimate Digital Income Guide"
theme = "geeky-curious"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "40"
# Robotstxt
enableRobotsTXT = true
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
# disqusShortname = "aicurious" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # example: ["fr"] for disable french language

[permalinks]
  page = "/:slug/"
  blog = "/:slug/"
  post = "/blog/:year/:month/:slug/"
  year = "/blog/:slug/"
  month = "/blog/:slug/"

[taxonomies]
  
  2011 = "2011"
  2013 = "2013"
  2014 = "2014"
  2015 = "2015"
  2017 = "2017"
  2018 = "2018"
  2019 = "2019"
  2020 = "2020"
  2021 = "2021"
  2022 = "2022"
  2023 = "2023"
  2024 = "2024"
  January = "January"
  February = "February"
  March = "March"
  April = "April"
  May = "May"
  June = "June"
  July = "July"
  August = "August"
  September = "September"
  October = "October"
  November = "November"
  December = "December"

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 75

# Set timeout to prevent exiting on building pages.
timeout = 180000

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # change to false to disable inclusion of rawHTML and math functions
      xhtml = false
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "monokai"
    tabWidth = 2
unsafe = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

############################ sitemap  ###########################
[sitemap]
  changeFreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0
