############# English navigation ##############

# main menu
[[main]]
  name = "Articles"
  url = ""
  weight = 10

[[main]]
  name = "Make Money Online"
  url = "/blog/make-money-online/"
  weight = 50

[[main]]
  name = "Creative Side Hustles"
  url = "/blog/creative-side-hustles/"
  weight = 60

[[main]]
  name = "Passive Income Ideas"
  url = "/blog/passive-income-ideas/"
  weight = 70



# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Archives"
url = "archives/"
weight = 3

[[footer]]
name = "About"
url = "about/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 6
