############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Passive Income Ideas"
url = "categories/passive-income-ideas/"
weight = 2

[[main]]
name = "Blogging"
url = "categories/blogging/"
weight = 3

[[main]]
name = "Side Hustles"
url = "categories/side-hustles/"
weight = 4

[[main]]
name = "Ecommerce"
url = "categories/ecommerce/"
weight = 5

[[main]]
name = "Investing"
url = "categories/investing/"
weight = 6

[[main]]
name = "Freelancing"
url = "categories/freelancing/"
weight = 7

[[main]]
name = "Social Media"
url = "categories/social-media/"
weight = 8

# footer menu
[[footer]]
name = "Blog"
url = "blog/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4

[[footer]]
name = "Archives"
url = "archives/"
weight = 5