############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Make Money Online Ideas"
url = "/blog/digital-income-ideas/"
weight = 2

[[main]]
name = "Creative Side Hustles"
url = "/blog/creative-side-hustles/"
weight = 3

[[main]]
name = "Passive Income Ideas"
url  = "/blog/passive-income-investments/"
weight = 4

# footer menu
[[footer]]
name = "Blog"
url = "/blog/"
weight = 1

[[footer]]
name = "About"
url = "/about/"
weight = 2

[[footer]]
name = "Contact"
url = "/contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 4

[[footer]]
name = "Archives"
url = "/archives/"
weight = 5