#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "252px"
# logo text will only show when logo is missing.
logo_text = "Earn Money Online"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Authentic earn money online guide, find side hustles, passive income ideas, online jobs & more. Find expert tips on building wealth & gaining financial freedom."
author = "Dejuan"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Seattle, Washington"
email = "jonesdejuan24@gmail.com"
# contact form action
contact_form_action = "https://formspree.io/f/xdoreeqg" # contact form works with https://formspree.io
# search
search = true

# featured post title
featured_post_title = "Featured Posts"
recent_post_title = "Recent Posts"
mainSections = ["blog"]
# about widget content
about_widget_content = "Visit us on Social Media!"
# footer content
footer_content = "Your Ultimate Make Money From Home Guide."
# copyright
copyright = 'Copyright © 2022 Earnonlinemoney.org. All Rights Reserved.'

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
# custom_script= "<script>console.log(\"Hello World\")</script>"


# Comment
talkyardServerUrl = ""
talkyardScriptUrl = ""

# Buy me a coffee
# Comment below line to disable
buyMeACoffeeId = "dejuanjones"

# Google Adsense
# adsenseDataAdClient = "ca-pub-9046870770761569"

codeLineNumbers = true


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Earn **Money** Online"
title_small = "Digital Side Hustles, Online Jobs"
image = "images/earn-money.png"
background_image = "/images/banner-bg-shape.svg"
content = "Expert earn money online guide for entrepreneurs, students, stay at home moms & dads. Find make money from home opportunities, side hustles, online jobs, & more!"
button_label = "Start"
button_link = "about/"

# Advertise
[advertisement]
image = "images/earn-internet-income.png"
link = "/blog"

# cookies
[cookies]
enable = true
expire_days = 30
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "newsletter", "recent-post", "categories"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "" # replace this code with yours


############################# social site ########################
# [[social]]
# title = "facebook"
# icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
# link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/moneyonline_fre/"

# [[social]]
# title = "instagram"
# icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#"

[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.facebook.com/earnmoneynowonline/"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/company/earn-money-online-free/"

# customize your color and font from here.
[variables]
color_primary = "#168118"
body_color = "#FFF"
text_color = "#424242"
text_dark = "#00274f"
text_light = "#999"
border_color = "#E1E1E1"
black = "#000"
white = "#FFF"
light = "#f2f2f2"